package entity;
// Generated Jan 28, 2016 5:30:30 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Comments generated by hbm2java
 */
public class Comments  implements java.io.Serializable {


     private Long commentId;
     private Posts posts;
     private Users users;
     private Date commentDate;
     private String commentContent;

    public Comments() {
    }

    public Comments(Posts posts, Users users, Date commentDate, String commentContent) {
       this.posts = posts;
       this.users = users;
       this.commentDate = commentDate;
       this.commentContent = commentContent;
    }
   
    public Long getCommentId() {
        return this.commentId;
    }
    
    public void setCommentId(Long commentId) {
        this.commentId = commentId;
    }
    public Posts getPosts() {
        return this.posts;
    }
    
    public void setPosts(Posts posts) {
        this.posts = posts;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Date getCommentDate() {
        return this.commentDate;
    }
    
    public void setCommentDate(Date commentDate) {
        this.commentDate = commentDate;
    }
    public String getCommentContent() {
        return this.commentContent;
    }
    
    public void setCommentContent(String commentContent) {
        this.commentContent = commentContent;
    }




}


