package entity;
// Generated Jan 28, 2016 5:30:30 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Long UId;
     private String UUsername;
     private String UPass;
     private String UFullname;
     private String UEmail;
     private Date URegistered;
     private Set postses = new HashSet(0);
     private Set commentses = new HashSet(0);

    public Users() {
    }

	
    public Users(String UUsername, String UPass, String UFullname, String UEmail, Date URegistered) {
        this.UUsername = UUsername;
        this.UPass = UPass;
        this.UFullname = UFullname;
        this.UEmail = UEmail;
        this.URegistered = URegistered;
    }
    public Users(String UUsername, String UPass, String UFullname, String UEmail, Date URegistered, Set postses, Set commentses) {
       this.UUsername = UUsername;
       this.UPass = UPass;
       this.UFullname = UFullname;
       this.UEmail = UEmail;
       this.URegistered = URegistered;
       this.postses = postses;
       this.commentses = commentses;
    }
   
    public Long getUId() {
        return this.UId;
    }
    
    public void setUId(Long UId) {
        this.UId = UId;
    }
    public String getUUsername() {
        return this.UUsername;
    }
    
    public void setUUsername(String UUsername) {
        this.UUsername = UUsername;
    }
    public String getUPass() {
        return this.UPass;
    }
    
    public void setUPass(String UPass) {
        this.UPass = UPass;
    }
    public String getUFullname() {
        return this.UFullname;
    }
    
    public void setUFullname(String UFullname) {
        this.UFullname = UFullname;
    }
    public String getUEmail() {
        return this.UEmail;
    }
    
    public void setUEmail(String UEmail) {
        this.UEmail = UEmail;
    }
    public Date getURegistered() {
        return this.URegistered;
    }
    
    public void setURegistered(Date URegistered) {
        this.URegistered = URegistered;
    }
    public Set getPostses() {
        return this.postses;
    }
    
    public void setPostses(Set postses) {
        this.postses = postses;
    }
    public Set getCommentses() {
        return this.commentses;
    }
    
    public void setCommentses(Set commentses) {
        this.commentses = commentses;
    }




}


